import { MODELS, subscribeModel, selectModel, loadModel, stopDownload, generate, unloadModel } from './browser-model.mjs';
import { readBackup, retrieve } from './study-data.mjs';
import { answerHosted } from './hosted-answer.mjs';
import { tutorInstructions, answerSchema, validateAnswer, validateQuestion } from './answer-contract.mjs';
const $=id=>document.getElementById(id);
let classes=[], selected='', task, busy=false, db, answerMode='device', modelPhase='idle';
const current=()=>classes.find(c=>c.id===selected);
const fail=e=>{$('study-error').textContent=e?.message||String(e);};
async function database(){if(db)return db;db=await new Promise((resolve,reject)=>{const r=indexedDB.open('coursekin-browser',1);r.onupgradeneeded=()=>r.result.createObjectStore('classes',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return db;}
async function transact(mode,operation){const db=await database();return new Promise((resolve,reject)=>{const t=db.transaction('classes',mode);const r=operation(t.objectStore('classes'));let result;r.onsuccess=()=>result=r.result;t.oncomplete=()=>resolve(result);const failed=()=>reject(t.error||Error('Browser storage could not save this change. Your saved class is unchanged.'));t.onerror=failed;t.onabort=failed;});}
async function save(c){await transact('readwrite',store=>store.put(c));const index=classes.findIndex(item=>item.id===c.id);if(index<0)classes.push(c);else classes[index]=c;}
function updateAnswerControls(){const loading=modelPhase==='loading';for(const radio of document.querySelectorAll('[name="answer-mode"]'))radio.disabled=busy||loading;for(const id of ['hosted-key','hosted-model','clear-key'])$(id).disabled=busy;$('model-select').disabled=busy||loading||modelPhase==='generating';$('download-model').disabled=busy||loading||modelPhase==='generating';}
function setBusy(value){busy=value;for(const id of ['ask','materials','class-select','class-name','backup','restore','delete-class'])$(id).disabled=value;$('class-form').querySelector('button').disabled=value;for(const button of $('documents').querySelectorAll('button'))button.disabled=value;$('stop-answer').hidden=!value;updateAnswerControls();}
function renderAnswerText(target,value){let offset=0;for(const match of value.matchAll(/\*\*([^*\n]+)\*\*/g)){target.append(document.createTextNode(value.slice(offset,match.index)));const emphasis=document.createElement('strong');emphasis.textContent=match[1];target.append(emphasis);offset=match.index+match[0].length;}target.append(document.createTextNode(value.slice(offset)));}
function render(){const chooser=$('class-select');chooser.replaceChildren(...classes.map(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=c.name;return o;}));chooser.value=selected;
 const c=current();$('documents').replaceChildren();$('conversation').replaceChildren();if(!c)return;
 for(const doc of c.documents){const li=document.createElement('li'),button=document.createElement('button');li.append(document.createTextNode(`${doc.name} · ${doc.pages.length} pages `));button.textContent='Remove';button.disabled=busy;button.addEventListener('click',async()=>{if(busy)return;try{await save({...c,documents:c.documents.filter(d=>d.id!==doc.id)});render();}catch(error){fail(error)}});li.append(button);$('documents').append(li);}
 for(const message of c.messages){const article=document.createElement('article'),h=document.createElement('strong'),text=document.createElement('pre');h.textContent=message.role==='user'?'You':'Coursekin';if(message.role==='assistant')renderAnswerText(text,message.text);else text.textContent=message.text;article.append(h,text);for(const source of message.sources||[]){const detail=document.createElement('details'),summary=document.createElement('summary'),quote=document.createElement('pre');summary.textContent=`[source:${source.id}] ${source.name}, page ${source.page}`;quote.textContent=source.text;detail.append(summary,quote);article.append(detail);}$('conversation').append(article);}
}
$('model-select').replaceChildren(...MODELS.map(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=m.label;return o;}));
$('model-select').addEventListener('change',e=>{try{selectModel(e.target.value)}catch(e){fail(e)}});
$('download-model').addEventListener('click',()=>loadModel().catch(fail));$('stop-download').addEventListener('click',stopDownload);
subscribeModel(s=>{modelPhase=s.phase;$('model-status').textContent=s.text;$('model-progress').hidden=s.phase!=='loading';$('model-progress').value=s.progress;$('stop-download').hidden=s.phase!=='loading';updateAnswerControls();});
for(const radio of document.querySelectorAll('[name="answer-mode"]'))radio.addEventListener('change',()=>{if(busy||modelPhase==='loading')return;answerMode=radio.value;if(answerMode==='device')$('hosted-key').value='';else unloadModel();$('model-panel').hidden=answerMode!=='device';$('hosted-panel').hidden=answerMode!=='hosted';$('study-error').textContent='';$('task-status').textContent=answerMode==='hosted'?'Hosted answers selected. Usage is billed to your OpenAI API account.':'Device answers selected. Your key was cleared.';});
$('clear-key').addEventListener('click',()=>{$('hosted-key').value='';$('task-status').textContent='API key cleared from this tab.';});
window.addEventListener('pagehide',()=>{$('hosted-key').value='';});
$('class-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;try{const name=$('class-name').value.trim();if(!name)return;const c={id:crypto.randomUUID(),name,documents:[],messages:[]};await save(c);selected=c.id;$('class-name').value='';render();}catch(e){fail(e)}});
$('class-select').addEventListener('change',e=>{selected=e.target.value;render()});
async function readFile(file){if(file.size>25*1024*1024)throw Error(`${file.name} exceeds 25 MB.`);const bytes=await file.arrayBuffer();let pages;
 if(/\.pdf$/i.test(file.name)){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@6.4.299/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.4.299/build/pdf.worker.mjs';const loading=pdfjs.getDocument({data:new Uint8Array(bytes)});try{const pdf=await loading.promise;if(pdf.numPages>1500)throw Error('Use a PDF with at most 1,500 pages.');pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();pages.push(content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join(''));}}finally{await loading.destroy();}}
 else if(/\.docx$/i.test(file.name)){const {unzipSync,strFromU8}=await import('https://cdn.jsdelivr.net/npm/fflate@0.8.3/esm/browser.js');const files=unzipSync(new Uint8Array(bytes)),xml=files['word/document.xml'];if(!xml)throw Error('This is not a readable DOCX document.');const doc=new DOMParser().parseFromString(strFromU8(xml),'application/xml');pages=[[...doc.getElementsByTagName('w:p')].map(p=>p.textContent).join('\n')];}
 else if(/\.(txt|md)$/i.test(file.name))pages=[new TextDecoder().decode(bytes)];else throw Error('Use PDF, DOCX, TXT or Markdown.');
 if(pages.join('').length>600000)throw Error('This document is too large. Split it into smaller files.');if(!pages.some(p=>p.trim()))throw Error('No readable text was found. Scanned pages need OCR first.');return {id:crypto.randomUUID(),name:file.name,pages};}
$('materials').addEventListener('change',async e=>{if(!current()||busy)return;setBusy(true);$('study-error').textContent='';const snapshot=current();try{const files=[...e.target.files];if(snapshot.documents.length+files.length>20)throw Error('Use at most 20 documents per class.');const docs=[];for(const file of files){$('task-status').textContent=`Reading ${file.name} locally…`;docs.push(await readFile(file));}await save({...snapshot,documents:[...snapshot.documents,...docs]});render();$('task-status').textContent='Materials saved on this device.';}catch(e){fail(e)}finally{setBusy(false);e.target.value='';}});
$('question-form').addEventListener('submit',async e=>{e.preventDefault();if(busy||!current())return;const submittedDraft=$('question').value,question=submittedDraft.trim();if(!question)return;const c=current(),sources=retrieve(c,question);setBusy(true);$('study-error').textContent='';task=new AbortController();try{
 if(!c.documents.length)throw Error('Add course materials first.');if(!sources.length)throw Error('No matching passages were found. Use terms from your materials or add the relevant source.');
 $('task-status').textContent=answerMode==='hosted'?'Reading selected passages with OpenAI…':'Reading relevant passages and answering on your device…';
 const input=validateQuestion({question,recentConversation:c.messages.slice(-4).map(m=>({role:m.role,text:m.text})),excerpts:sources});
 const output=answerMode==='hosted'?await answerHosted(input,{apiKey:$('hosted-key').value,model:$('hosted-model').value,signal:task.signal}):await generate([{role:'system',content:tutorInstructions+' Return exactly one compact JSON object with two fields: "answer" (a string) and "sourceIds" (an array of cited excerpt ID strings). Include both fields and no other text. /no_think'},{role:'user',content:JSON.stringify(input)}],{schema:answerSchema(sources),maxTokens:1600,signal:task.signal});
 task.signal.throwIfAborted();
 const {answer,sourceIds:ids}=validateAnswer(output.value,sources);
 await save({...c,messages:[...c.messages,{role:'user',text:question},{role:'assistant',text:answer,sources:sources.filter(s=>ids.includes(s.id))}]});if($('question').value===submittedDraft)$('question').value='';render();$('task-status').textContent='Answer saved. Check the cited excerpts against your materials.';
 }catch(e){if(e.name==='AbortError')$('task-status').textContent='Answer stopped. Your materials and prior conversation are unchanged.';else fail(e);}finally{task=null;setBusy(false);}});
$('stop-answer').addEventListener('click',()=>task?.abort());
$('backup').addEventListener('click',()=>{const c=current();if(!c)return;const url=URL.createObjectURL(new Blob([JSON.stringify({format:'coursekin-browser',version:1,...c},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='coursekin-class.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('restore').addEventListener('change',async e=>{if(busy)return;setBusy(true);$('study-error').textContent='';try{const file=e.target.files[0];if(!file)return;if(file.size>30*1024*1024)throw Error('Backup is too large.');const c={...readBackup(JSON.parse(await file.text())),id:crypto.randomUUID()};await transact('readwrite',store=>store.put(c));classes.push(c);selected=c.id;render();}catch(e){fail(e)}finally{e.target.value='';setBusy(false)}});
$('delete-class').addEventListener('click',async()=>{const c=current();if(busy||!c||!confirm(`Delete ${c.name} and its materials from this browser?`))return;try{await transact('readwrite',store=>store.delete(c.id));classes=classes.filter(x=>x.id!==c.id);selected=classes[0]?.id||'';render();}catch(error){fail(error)}});
try{classes=await transact('readonly',store=>store.getAll());selected=classes[0]?.id||'';render();}catch(e){fail(Error('Browser storage is unavailable. Enable local site storage to save your classes.'));}
